namespace:
  name: staging
 
service:
  port: 3111
  type: ClusterIP
  protocol: TCP
  targetPort: 3111

image:
  repository: afislonge/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

containerPort: 3111

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    memory: 128Mi
    cpu: 500m

livenessProbe: 
  httpGet:        
    path: /healthz
    port: 3111
readinessProbe:        
  httpGet:            
    path: /healthz
    port: 3111
