namespace:
  name: prod
 
service:
  port: 7111
  type: ClusterIP
  protocol: TCP
  targetPort: 3111

image:
  repository: afislonge/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5

containerPort: 3111

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    memory: 256Mi
    cpu: 500m

livenessProbe: 
  httpGet:        
    path: /healthz
    port: 3111
readinessProbe:        
  httpGet:            
    path: /healthz
    port: 3111
